import {snapshotWaiver,updateWaiver} from './waivers';
import {stripeConfig,organization,settingsView,saveSettings,charges} from './settings';
import {all,one,run,q,db,id,now,log,mail,config} from './db';
import {user,hash,password,session,rate} from './auth';
import {ageAt,canManage,validateWaiver,waiverText,paymentStatus,csvCell} from '../rules';
import {demoSeasons} from '../demo';
const safe=(u:any)=>u?{id:u.id,name:u.name,email:u.email,role:u.role,profile:u.profile,verified:u.verified}:null;
const fail=(s:string,code=400)=>{throw Object.assign(Error(s),{status:code})};
const integer=(x:any,min=0)=>{const n=Number(x);if(!Number.isSafeInteger(n)||n<min)fail('Please enter a valid amount or number.');return n;};
const escape=(s:any)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
async function owned(uid:string,rid:string,admin:boolean){const r=await one('SELECT r.*,p.name player_name,p.dob,p.data player_data,u.name parent_name,u.email,s.name season_name,s.division FROM registrations r JOIN players p ON p.id=r.player_id JOIN users u ON u.id=r.owner JOIN seasons s ON s.id=r.season_id WHERE r.id=?'+(admin?'':' AND r.owner=?'),...admin?[rid]:[rid,uid]);if(!r)fail('Registration not found.',404);return r;}
async function seasonRows(admin=false){const rows=await all(`SELECT s.*,(SELECT count(*) FROM registrations r WHERE r.season_id=s.id AND r.status NOT IN ('Cancelled','Waitlisted','Waiver only')) enrolled FROM seasons s ${admin?'':"WHERE s.archived=0 AND s.status!='Draft'"} ORDER BY s.start`);return rows.map(s=>({...s,status:s.status==='Open'&&s.enrolled>=s.capacity?'Full':s.status}));}
async function registrations(uid:string,admin:boolean){return all(`SELECT r.*,p.name player_name,p.dob,p.data player_data,u.name parent_name,u.email,s.name season_name,s.division,CASE WHEN w.id IS NULL THEN 'Missing' ELSE 'Signed' END waiver_status,w.signed FROM registrations r JOIN players p ON p.id=r.player_id JOIN users u ON u.id=r.owner JOIN seasons s ON s.id=r.season_id LEFT JOIN signed_waivers w ON w.registration_id=r.id ${admin?'':'WHERE r.owner=?'} ORDER BY r.created DESC`,...admin?[]:[uid]);}
async function quote(b:any){const s=await one('SELECT * FROM seasons WHERE id=? AND archived=0',b.seasonId);if(!s)fail('Season not found.',404);const d=b.promo?await one('SELECT * FROM discount_codes WHERE code=? AND active=1',String(b.promo).trim().toUpperCase()):null;if(b.promo&&!d)fail('This promo code is not valid.');const discount=d?Math.floor(s.price*d.percent/100):0;return charges(s.price,discount,await organization());}
async function stripe(path:string,body?:any,key?:string){const c=await stripeConfig();if(!c.STRIPE_SECRET_KEY)fail('Online payments are not connected yet. Please contact the club to arrange payment.',503);const r=await fetch('https://api.stripe.com/v1/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+c.STRIPE_SECRET_KEY,...body?{'Content-Type':'application/x-www-form-urlencoded'}:{},...key?{'Idempotency-Key':key}:{}},body:body?new URLSearchParams(body):undefined});const result=await r.json() as any;if(!r.ok)fail(result.error?.message||'Payment provider unavailable.',502);return result;}
export async function handle(req:Request,path:string){const url=new URL(req.url),method=req.method;let b:any={};if(method==='POST'){if(req.headers.get('origin')&&req.headers.get('origin')!==url.origin)fail('Request origin is not allowed.',403);if(Number(req.headers.get('content-length')||0)>100000)fail('Request is too large.',413);b=await req.json();}const u=await user(req),admin=!!u&&canManage(u.role);const c=config();
if(path==='public')return {seasons:await seasonRows(false),organization:await organization(),user:safe(u)};
if(path==='bootstrap')return {user:safe(u),seasons:await seasonRows(admin),registrations:u?await registrations(u.id,admin):[],players:u?await all('SELECT * FROM players'+(admin?'':' WHERE owner=?'),...admin?[]:[u.id]):[],logs:admin?await all('SELECT a.*,u.name actor FROM audit_logs a LEFT JOIN users u ON u.id=a.actor ORDER BY a.created DESC LIMIT 100'):[],users:u?.role==='admin'?await all('SELECT id,name,email,role,verified FROM users'):[],settings:u?.role==='admin'?await settingsView():undefined,integrations:{Stripe:!!(await stripeConfig()).STRIPE_SECRET_KEY,Email:!!c.RESEND_API_KEY,'Google Sheets':!!c.GOOGLE_CLIENT_ID}};
if(path.startsWith('auth/')){
if(method!=='POST')fail('Method not allowed.',405);await rate(req,'auth');
const email=String(b.email||'').trim().toLowerCase();
if(path==='auth/signup'){if(!c.RESEND_API_KEY||!c.EMAIL_FROM)fail('New accounts will open when the club connects email verification. Please contact the administrator.',503);if(!/^\S+@\S+\.\S+$/.test(email)||!b.name||b.password?.length<12)fail('Enter your name, a valid email, and a password of at least 12 characters.');if(await one('SELECT id FROM users WHERE email=?',email))return {message:'If this address can be registered, you will receive a verification email.'};const uid=id();await run('INSERT INTO users(id,email,name,password,created) VALUES(?,?,?,?,?)',uid,email,String(b.name).slice(0,120),await password(b.password),now());const token=id()+id();await run('INSERT INTO tokens VALUES(?,?,?,?)',await hash(token),uid,'verify',Date.now()+86400000);await mail({id:uid,email},'Verify your BSTC email',`Welcome to BSTC. Verify your email: ${url.origin}/?verify=${token}\nThis link expires in 24 hours.`);return {message:'Check your email to verify your account before signing in.'};}
if(path==='auth/login'){const found=await one('SELECT * FROM users WHERE email=?',email);const actual=await password(String(b.password||''),found?.password?.split(':')[0]||'dummy-salt');if(!found?.password||actual!==found.password)fail('The email or password is incorrect.',401);if(!found.verified)fail('Please verify your email before signing in.',403);return Response.json({user:safe(found)},{headers:{'Set-Cookie':await session(found.id)}});}
if(path==='auth/logout'){const t=req.headers.get('cookie')?.match(/bstc_session=([^;]+)/)?.[1];if(t)await run('DELETE FROM sessions WHERE id=?',await hash(t));return Response.json({ok:true},{headers:{'Set-Cookie':'bstc_session=; Max-Age=0; Secure; HttpOnly; SameSite=Lax; Path=/'}});}
if(path==='auth/verify'||path==='auth/reset'){const token=await one('SELECT * FROM tokens WHERE id=? AND kind=? AND expires>?',await hash(String(b.token||'')),path==='auth/verify'?'verify':'reset',Date.now());if(!token)fail('This link is invalid or has expired.');if(path==='auth/verify')await run('UPDATE users SET verified=1 WHERE id=?',token.user_id);else{if(b.password?.length<12)fail('Use a password of at least 12 characters.');await db().batch([q('UPDATE users SET password=? WHERE id=?',await password(b.password),token.user_id),q('DELETE FROM sessions WHERE user_id=?',token.user_id)]);}await run('DELETE FROM tokens WHERE id=?',token.id);return {message:path==='auth/reset'?'Password updated. You can now sign in.':'Email verified.'};}
if(path==='auth/forgot'){if(!c.RESEND_API_KEY)fail('Password reset email is not connected yet.',503);const found=await one('SELECT * FROM users WHERE email=?',email);if(found){const t=id()+id();await run('INSERT INTO tokens VALUES(?,?,?,?)',await hash(t),found.id,'reset',Date.now()+3600000);await mail(found,'Reset your BSTC password',`Reset your password: ${url.origin}/?reset=${t}\nThis link expires in one hour.`);}return {message:'If an account exists for that email, a password reset link has been sent.'};}
fail('Not found.',404);
}
if(path==='quote')return quote(b);
if(!u)fail('Please sign in to continue.',401);
if(method==='POST')await rate(req,'write:'+u.id);
if(path==='players'&&method==='POST'){if(!b.name||!/^\d{4}-\d{2}-\d{2}$/.test(b.dob)||b.dob>now().slice(0,10)||!b.emergencyName||!b.emergencyPhone||!b.phone||!b.address)fail('Complete the player’s legal name, date of birth, address, phone, and emergency contact.');const pid=b.id||id();if(b.id){const p=await one('SELECT * FROM players WHERE id=?',pid);if(!p||(!admin&&p.owner!==u.id))fail('Player not found.',404);await run('UPDATE players SET name=?,dob=?,data=? WHERE id=?',String(b.name).slice(0,120),b.dob,JSON.stringify(b),pid);}else await db().batch([q('INSERT INTO players VALUES(?,?,?,?,?)',pid,u.id,String(b.name).slice(0,120),b.dob,JSON.stringify(b)),q('INSERT INTO parent_players VALUES(?,?,?,?)',id(),u.id,pid,'Parent / guardian or self')]);await log(u.id,'Saved player',pid);return {id:pid};}
if(path==='profile'&&method==='POST'){if(!b.name)fail('Your name is required.');await run('UPDATE users SET name=?,profile=? WHERE id=?',String(b.name).slice(0,120),JSON.stringify(b),u.id);return {ok:true};}
if(path==='register'&&method==='POST'){
if(!u.verified)fail('Verify your email before registering.',403);try{validateWaiver(b)}catch(e:any){fail(e.message)}const p=await one('SELECT * FROM players WHERE id=? AND owner=?',b.playerId,u.id);if(!p)fail('Select a player from your family.');const s=await one('SELECT * FROM seasons WHERE id=? AND archived=0',b.seasonId);const today=now().slice(0,10);if(!s||!['Open','Full'].includes(s.status)||today<s.open||today>s.close)fail('Registration for this season is not open.');if(s.version!==b.waiverVersion)fail('The waiver has changed. Reopen registration and review the latest waiver.');const age=ageAt(p.dob,s.start);if(age<s.min_age||age>s.max_age)fail(`This season is for players ages ${s.min_age}–${s.max_age} at the start of the season.`);if(b.relationship==='Adult player'&&ageAt(p.dob,today)<18)fail('A parent or guardian must sign for a minor.');if(b.date!==today)fail('Confirm today’s date for your electronic signature.');for(const x of JSON.parse(s.questions)){if(x.required&&!String(b.answers?.[x.label]||'').trim())fail('Please complete: '+x.label);}if(await one('SELECT id FROM registrations WHERE player_id=? AND season_id=?',p.id,s.id))fail('This player already has a registration for this season.');const cost=await quote(b);if(b.quote&&b.quote.total!==cost.total)fail('The price or discount has changed. Review the latest total before continuing.');const rid=id(),timestamp=now();try{await db().batch([q(`INSERT INTO registrations(id,player_id,season_id,owner,status,payment_status,amount,paid,created,answers) SELECT ?,?,?,?,CASE WHEN ?=1 THEN 'Waiver only' WHEN (SELECT COUNT(*) FROM registrations WHERE season_id=? AND status NOT IN ('Cancelled','Waitlisted','Waiver only'))>=capacity OR status='Full' THEN 'Waitlisted' ELSE 'Confirmed' END,?, ?,0,?,? FROM seasons WHERE id=? AND status IN ('Open','Full') AND archived=0 AND version=?`,rid,p.id,s.id,u.id,b.waiverOnly?1:0,s.id,cost.total===0?'Waived':'Unpaid',cost.total,timestamp,JSON.stringify({...b.answers,notes:b.notes,_charges:cost}),s.id,s.version),q('INSERT INTO signed_waivers SELECT ?,id,?,?,?,?,?,? FROM registrations WHERE id=?',id(),s.waiver,s.version,b.signer.trim(),b.relationship,timestamp,b.date,rid)]);}catch{fail('This player may already be registered. Refresh and check My registrations.');}const r=await one('SELECT * FROM registrations WHERE id=?',rid);if(!r)fail('The season changed. Please try again.');await mail(u,'BSTC registration confirmation',`${p.name} is ${r.status.toLowerCase()} for ${s.name}.\nRegistration: ${rid}\n${b.waiverOnly?'Waiver filed only — no spot reserved or payment required now.':'Amount due: $'+(cost.total/100).toFixed(2)}\nYour signed waiver is available in your portal.`);await log(u.id,'Created registration',rid);return r;
}
if(path==='complete-registration'&&method==='POST'){const r=await owned(u.id,b.id,admin);if(!['Waiver only','Waitlisted'].includes(r.status))fail('This registration is already active or cancelled.');const season=await one('SELECT * FROM seasons WHERE id=?',r.season_id);const today=now().slice(0,10);if(!season||season.archived||!['Open','Full'].includes(season.status)||today<season.open||today>season.close)fail('Registration is not open for this season.');if(!await one('SELECT id FROM signed_waivers WHERE registration_id=?',r.id))fail('A signed waiver is required.');await run("UPDATE registrations SET status=CASE WHEN (SELECT count(*) FROM registrations WHERE season_id=? AND status NOT IN ('Cancelled','Waitlisted','Waiver only'))<(SELECT capacity FROM seasons WHERE id=?) AND (SELECT status FROM seasons WHERE id=?)='Open' THEN 'Confirmed' ELSE 'Waitlisted' END WHERE id=? AND status IN ('Waiver only','Waitlisted')",r.season_id,r.season_id,r.season_id,r.id);const updated=await one('SELECT * FROM registrations WHERE id=?',r.id);await log(u.id,'Completed waiver-only registration: '+updated.status,r.id);return updated;}
if(path==='checkout'&&method==='POST'){if(!b||Object.keys(b).some(k=>k!=='registrationId')||typeof b.registrationId!=='string')fail('Checkout accepts only a registration ID. Enter payment details on Stripe.');const r=await owned(u.id,b.registrationId,admin);if(['Waitlisted','Cancelled','Waiver only'].includes(r.status)||r.payment_status==='Waived')fail('This registration is not eligible for payment.');const amount=r.amount-r.paid;if(amount<=0)fail('This registration has no balance due.');const checkout=await stripe('checkout/sessions',{'mode':'payment','ui_mode':'hosted','customer_email':r.email,'client_reference_id':r.id,'metadata[registration_id]':r.id,'payment_intent_data[metadata][registration_id]':r.id,'line_items[0][price_data][currency]':'usd','line_items[0][price_data][unit_amount]':String(amount),'line_items[0][price_data][product_data][name]':r.season_name+' registration','line_items[0][quantity]':'1','success_url':url.origin+'/portal/registrations?payment=success','cancel_url':url.origin+'/portal/registrations?payment=cancelled'},'checkout-'+r.id+'-'+r.paid+'-'+Math.floor(Date.now()/1800000));if(typeof checkout.url!=='string'||!checkout.url.startsWith('https://checkout.stripe.com/'))fail('Secure checkout is unavailable. Please try again later.',502);await run("UPDATE registrations SET payment_status='Pending' WHERE id=? AND paid=0",r.id);return {url:checkout.url};}
if(path.startsWith('registrations/')&&method==='GET'){const r=await owned(u.id,path.split('/')[1],admin);return {...r,player:{data:r.player_data},payments:await all('SELECT * FROM payments WHERE registration_id=? ORDER BY created DESC',r.id),waiver:await one('SELECT * FROM signed_waivers WHERE registration_id=?',r.id),notes:admin?await all('SELECT * FROM admin_notes WHERE registration_id=? ORDER BY created DESC',r.id):undefined};}
if((path.startsWith('waiver/')||path.startsWith('receipt/'))&&method==='GET'){const r=await owned(u.id,path.split('/')[1],admin);const w=await one('SELECT * FROM signed_waivers WHERE registration_id=?',r.id);const pay=await all('SELECT * FROM payments WHERE registration_id=?',r.id);if(path.startsWith('waiver/')&&!w)fail('No signed waiver found.',404);const content=path.startsWith('waiver/')?`<h1>Signed participation waiver</h1><p>Player: ${escape(r.player_name)} · ${escape(r.season_name)}</p><pre>${escape(w.text)}</pre><hr><p>Electronic signature: <b>${escape(w.signer)}</b></p><p>Relationship: ${escape(w.relationship)}<br>Confirmed date: ${escape(w.date)}<br>Recorded at (UTC): ${escape(w.signed)}<br>Waiver version: ${w.version}<br>Registration: ${escape(r.id)}</p>`:`<h1>Registration payment statement</h1><p>${escape(r.player_name)} · ${escape(r.season_name)}</p><p>Status: ${escape(r.payment_status)}</p><p>Registration total: $${(r.amount/100).toFixed(2)}<br>Net paid: $${(r.paid/100).toFixed(2)}<br>Balance: $${(Math.max(0,r.amount-r.paid)/100).toFixed(2)}</p>${pay.map(p=>`<p>${escape(p.created)} · ${escape(p.method)} · $${(p.amount/100).toFixed(2)}</p>`).join('')}<p>Registration ${escape(r.id)}</p>`;return new Response(`<!doctype html><html><head><meta charset="utf-8"><title>BSTC · Registration document</title><style>body{font:16px/1.7 Arial;max-width:750px;margin:40px auto;padding:20px;color:#183e28}pre{white-space:pre-wrap;font:inherit}button{padding:12px;background:#176b40;color:white;border:0;border-radius:5px}@media print{button{display:none}}</style></head><body><h2>BSTC · Brazilian Soccer Training Center</h2>${content}<button onclick="window.print()">Print / save as PDF</button></body></html>`,{headers:{'Content-Type':'text/html;charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});}
if(path==='deletion-request'&&method==='POST'){await log(u.id,'Requested account deletion',u.id);await mail(u,'BSTC account deletion request received','Your account deletion request has been recorded. The club administrator will review applicable record-retention obligations.');return {ok:true};}
if(!admin)fail('Administrator or staff access is required.',403);
if(path.startsWith('waivers/history/')&&method==='GET'){const sid=path.split('/')[2];const season=await one('SELECT id,name,waiver,version FROM seasons WHERE id=?',sid);if(!season)fail('Season not found.',404);return {season,versions:await all('SELECT * FROM waiver_versions WHERE season_id=? ORDER BY version DESC',sid)};}
if(path==='notes'&&method==='POST'){await owned(u.id,b.id,true);if(!b.text?.trim())fail('Enter a note.');await run('INSERT INTO admin_notes VALUES(?,?,?,?,?)',id(),b.id,u.id,b.text.slice(0,5000),now());await log(u.id,'Added internal note',b.id);return {ok:true};}
if(path==='reminder'&&method==='POST'){const r=await owned(u.id,b.id,true);await mail({id:r.owner,email:r.email},'BSTC registration reminder',`Please review your registration for ${r.season_name}.\nOutstanding balance: $${(Math.max(0,r.amount-r.paid)/100).toFixed(2)}.\nSign in to your BSTC account to review your status.`);await log(u.id,'Sent registration reminder',r.id);return {ok:true};}
if(path==='registrations/cancel'&&method==='POST'){const cancelled=await owned(u.id,b.id,true);await run("UPDATE registrations SET status='Cancelled' WHERE id=?",b.id);await log(u.id,'Cancelled registration',b.id);if(!['Cancelled','Waitlisted','Waiver only'].includes(cancelled.status)){const next=await one("SELECT r.*,u.email FROM registrations r JOIN users u ON u.id=r.owner WHERE r.season_id=? AND r.status='Waitlisted' ORDER BY r.created,r.id LIMIT 1",cancelled.season_id);if(next)await mail({id:next.owner,email:next.email},'A BSTC soccer spot has opened','A spot has opened in '+cancelled.season_name+'. Sign in and complete your registration. Availability is checked when you continue.');}return {ok:true};}
if(path==='registrations/edit'&&method==='POST'){const r=await owned(u.id,b.id,true);if(!['Confirmed','Waitlisted','Cancelled','Waiver only'].includes(b.status))fail('Invalid registration status.');let answers;try{answers=JSON.parse(b.answers||'{}');}catch{fail('Answers must be valid JSON.');}const result=await run("UPDATE registrations SET status=?,answers=? WHERE id=? AND (?!='Confirmed' OR status='Confirmed' OR (SELECT count(*) FROM registrations WHERE season_id=? AND status NOT IN ('Cancelled','Waitlisted','Waiver only'))<(SELECT capacity FROM seasons WHERE id=?))",b.status,JSON.stringify(answers),r.id,b.status,r.season_id,r.season_id);if(!result.meta.changes)fail('This season has reached capacity.');await log(u.id,'Edited registration',r.id);return {ok:true};}
if(path==='export'&&method==='POST'){const rows=await registrations(u.id,true),filtered=Array.isArray(b.ids)?rows.filter(r=>b.ids.includes(r.id)):rows;const map:any={'Registration ID':(r:any)=>r.id,'Season':(r:any)=>r.season_name,'Player name':(r:any)=>r.player_name,'Date of birth':(r:any)=>r.dob,'Division':(r:any)=>r.division,'Parent/guardian name':(r:any)=>r.parent_name,'Email':(r:any)=>r.email,'Phone number':(r:any)=>JSON.parse(r.player_data||'{}').phone,'Emergency contact':(r:any)=>{const p=JSON.parse(r.player_data||'{}');return `${p.emergencyName||''} ${p.emergencyPhone||''}`},'Registration date':(r:any)=>r.created,'Waiver status':(r:any)=>r.waiver_status,'Waiver signature date':(r:any)=>r.signed,'Payment status':(r:any)=>r.payment_status,'Amount due':(r:any)=>r.payment_status==='Waived'||r.status==='Waiver only'?0:Math.max(0,r.amount-r.paid)/100,'Amount paid':(r:any)=>r.paid/100,'Payment date':(r:any)=>r.payment_date,'Registration status':(r:any)=>r.status};const cols=(b.columns||[]).filter((x:string)=>map[x]);if(!cols.length)fail('Select export columns.');for(const r of filtered)r.payment_date=(await one('SELECT MAX(created) date FROM payments WHERE registration_id=?',r.id))?.date;const values=[cols,...filtered.map(r=>cols.map((x:string)=>map[x](r)??''))];await log(u.id,'Exported '+filtered.length+' registrations',b.format);if(b.format==='xlsx'){const {xlsx}=await import('./xlsx');return new Response(xlsx(values),{headers:{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Cache-Control':'no-store'}});}return new Response('\uFEFF'+values.map(row=>row.map(csvCell).join(',')).join('\r\n'),{headers:{'Content-Type':'text/csv;charset=utf-8','Cache-Control':'no-store'}});}
if(u.role!=='admin')fail('Only administrators can perform this action.',403);
if(path==='waivers/save'&&method==='POST'){const result=await updateWaiver(b.seasonId,b.text,b.version,u.id);if(!result.unchanged)await log(u.id,'Published waiver version '+result.version,b.seasonId);return result;}
if(path==='settings'&&method==='POST'){const result=await saveSettings(b);await log(u.id,'Updated organization and payment settings','settings');return result;}
if(path==='waive-fee'&&method==='POST'){const r=await owned(u.id,b.id,true);if(!b.reason?.trim())fail('Enter a reason for waiving the fee.');await run("UPDATE registrations SET payment_status='Waived' WHERE id=?",r.id);await log(u.id,'Waived outstanding fee',r.id);await run('INSERT INTO admin_notes VALUES(?,?,?,?,?)',id(),r.id,u.id,'Fee waived: '+b.reason,now());return {ok:true};}
if(path==='seasons'&&method==='POST'){for(const k of ['name','description','start','end','open','close','days','time','location','division','waiver'])if(!b[k]||typeof b[k]!=='string')fail('Complete '+k+'.');if(b.start>b.end||b.open>b.close)fail('End dates must be after start dates.');if(!['Draft','Open','Full','Closed','Completed'].includes(b.status))fail('Invalid season status.');const questions=JSON.parse(b.questions||'[]');if(!Array.isArray(questions)||questions.some(x=>typeof x.label!=='string'||typeof x.required!=='boolean'))fail('Questions must include a label and a true / false required value.');const sid=b.id||id(),old=b.id?await one('SELECT * FROM seasons WHERE id=?',b.id):null;if(b.id&&!old)fail('Season not found.');const capacity=integer(b.capacity,1);const enrolled=await one("SELECT count(*) n FROM registrations WHERE season_id=? AND status NOT IN ('Cancelled','Waitlisted','Waiver only')",sid);if(capacity<enrolled.n)fail('Capacity cannot be less than the current roster.');if(Number(b.min_age)>Number(b.max_age))fail('Minimum age must not exceed maximum age.');const vals=[b.name,b.description,b.status,b.start,b.end,b.open,b.close,b.days,b.time,b.location,integer(b.price),capacity,integer(b.min_age),integer(b.max_age),b.division,b.waiver,old?old.version+Number(old.waiver!==b.waiver):1,JSON.stringify(questions)];if(old)await db().batch([snapshotWaiver(sid,u.id),q('UPDATE seasons SET name=?,description=?,status=?,start=?,end=?,open=?,close=?,days=?,time=?,location=?,price=?,capacity=?,min_age=?,max_age=?,division=?,waiver=?,version=?,questions=? WHERE id=?',...vals,sid),snapshotWaiver(sid,u.id)]);else await run('INSERT INTO seasons(id,name,description,status,start,end,open,close,days,time,location,price,capacity,min_age,max_age,division,waiver,version,questions) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',sid,...vals);await log(u.id,'Saved season',sid);return {id:sid};}
if(path==='discounts'&&method==='POST'){if(!/^[A-Z0-9_-]{2,30}$/i.test(b.code||''))fail('Use 2–30 letters, numbers, underscores or dashes.');const percent=integer(b.percent);if(percent>100)fail('Discount must be between 0 and 100 percent.');await run('INSERT INTO discount_codes VALUES(?,?,1) ON CONFLICT(code) DO UPDATE SET percent=excluded.percent,active=1',b.code.toUpperCase(),percent);await log(u.id,'Saved discount code',b.code.toUpperCase());return {ok:true};}
if(path==='seasons/delete'&&method==='POST'){const count=await one('SELECT count(*) n FROM registrations WHERE season_id=?',b.id);if(count.n)await run("UPDATE seasons SET archived=1,status='Closed' WHERE id=?",b.id);else await db().batch([q('DELETE FROM waiver_versions WHERE season_id=? AND NOT EXISTS(SELECT 1 FROM registrations WHERE season_id=?)',b.id,b.id),q('DELETE FROM seasons WHERE id=? AND NOT EXISTS(SELECT 1 FROM registrations WHERE season_id=?)',b.id,b.id)]);await log(u.id,count.n?'Archived season':'Deleted unused season',b.id);return {ok:true};}
if(path==='seasons/archive'&&method==='POST'){await run("UPDATE seasons SET archived=1,status='Closed' WHERE id=?",b.id);await log(u.id,'Archived season',b.id);return {ok:true};}
if(path==='payments'&&method==='POST')fail('Payments are online-only. Use secure Stripe Checkout.',405);
if(path==='refunds'&&method==='POST'){const r=await owned(u.id,b.registrationId,true),amount=integer(b.amount,1);if(amount>r.paid)fail('Refund exceeds the net amount paid.');if(!b.reference)fail('A refund reason is required.');const pay=await all('SELECT p.*,p.amount-COALESCE((SELECT sum(amount) FROM refunds WHERE payment_id=p.id),0) remaining FROM payments p WHERE registration_id=? ORDER BY created DESC',r.id);const eligible=pay.find(p=>p.remaining>=amount);if(!eligible)fail('Split this refund into amounts that match the original payments.');const refundId=String(b.requestId||id());if(await one('SELECT id FROM refunds WHERE id=?',refundId))return {ok:true};let reference='offline-'+refundId;if(eligible.method==='Stripe'){const original=await stripe('checkout/sessions/'+eligible.reference);const result=await stripe('refunds',{payment_intent:original.payment_intent,amount:String(amount)},'refund-'+refundId);reference=result.id;if(result.status!=='succeeded')fail('Refund is pending at Stripe. Review the provider dashboard before recording a completed refund.');}await db().batch([q('INSERT INTO refunds SELECT ?,id,?,?,?,? FROM payments WHERE id=? AND amount-COALESCE((SELECT sum(amount) FROM refunds WHERE payment_id=?),0)>=?',refundId,amount,reference,b.reference,now(),eligible.id,eligible.id,amount),q("UPDATE registrations SET paid=paid-?,payment_status=CASE WHEN paid-?=0 THEN 'Refunded' ELSE 'Partially Paid' END WHERE id=? AND EXISTS(SELECT 1 FROM refunds WHERE id=?)",amount,amount,r.id,refundId)]);if(!await one('SELECT id FROM refunds WHERE id=?',refundId))fail('Refund balance changed. Review transactions.');await log(u.id,'Refunded payment',r.id);return {ok:true};}
if(path==='users/role'&&method==='POST'){if(b.id===u.id)fail('You cannot change your own role.');if(!['admin','staff','parent'].includes(b.role))fail('Invalid role.');await run('UPDATE users SET role=? WHERE id=?',b.role,b.id);await log(u.id,'Changed user role to '+b.role,b.id);return {ok:true};}
if(path==='seed'&&method==='POST'){if((await one('SELECT count(*) n FROM seasons')).n)fail('Sample seasons can only be loaded into an empty database.');for(const s of demoSeasons)await run('INSERT INTO seasons(id,name,description,status,start,end,open,close,days,time,location,price,capacity,min_age,max_age,division,waiver,version,questions) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',id(),s.name,s.description,'Draft',s.start,s.end,s.open,s.close,s.days,s.time,s.location,s.price,s.capacity,s.min_age,s.max_age,s.division,waiverText,1,'[]');await log(u.id,'Loaded sample draft seasons','seasons');return {ok:true};}
fail('This action is not available.',404);
}
