import {all,config,run} from './db';
const names={stripeSecretKey:'STRIPE_SECRET_KEY',stripeWebhookSecret:'STRIPE_WEBHOOK_SECRET',stripePublishableKey:'STRIPE_PUBLISHABLE_KEY'} as const;
async function encryptionKey(){const secret=config().AUTH_SECRET;if(!secret||secret.length<32)throw Object.assign(Error('The administrator must configure AUTH_SECRET before saving encrypted payment credentials.'),{status:503});const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(secret+':bstc-settings'));return crypto.subtle.importKey('raw',hash,'AES-GCM',false,['encrypt','decrypt']);}
export async function seal(value:string){const iv=crypto.getRandomValues(new Uint8Array(12)),encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv},await encryptionKey(),new TextEncoder().encode(value));return 'v1.'+btoa(String.fromCharCode(...iv))+'.'+btoa(String.fromCharCode(...new Uint8Array(encrypted)));}
async function unseal(value:string){const [version,iv,body]=value.split('.');if(version!=='v1')throw Error('Unsupported encrypted credential.');return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:Uint8Array.from(atob(iv),c=>c.charCodeAt(0))},await encryptionKey(),Uint8Array.from(atob(body),c=>c.charCodeAt(0))));}
export async function stripeConfig(){const c={...config()};const rows=await all("SELECT * FROM settings WHERE key LIKE 'stripe%'");for(const row of rows){const envKey=names[row.key as keyof typeof names];if(envKey&&row.value)c[envKey]=row.key==='stripePublishableKey'?row.value:await unseal(row.value);}return c;}
export async function organization(){const row=await all("SELECT value FROM settings WHERE key='organization'");return {orgName:'Brazilian Soccer Training Center',contactEmail:'',contactPhone:'',processingFeePercent:0,processingFeeFixed:0,taxPercent:0,...row.length?JSON.parse(row[0].value):{}};}
export async function settingsView(){const c=await stripeConfig();return {...await organization(),stripePublishableKey:c.STRIPE_PUBLISHABLE_KEY||'',stripeConfigured:!!c.STRIPE_SECRET_KEY,stripeSecretHint:c.STRIPE_SECRET_KEY?'••••'+c.STRIPE_SECRET_KEY.slice(-4):'',webhookConfigured:!!c.STRIPE_WEBHOOK_SECRET,encryptionReady:!!config().AUTH_SECRET};}
export async function saveSettings(b:any){const current=await organization();for(const key of ['processingFeePercent','processingFeeFixed','taxPercent'])if(!Number.isFinite(Number(b[key]))||Number(b[key])<0||Number(b[key])>(key==='processingFeeFixed'?100:30))throw Object.assign(Error('Enter valid fees and tax rates (0–30%, fixed fee up to $100).'),{status:400});if(!b.orgName?.trim())throw Object.assign(Error('Organization name is required.'),{status:400});if(b.contactEmail&&!/^\S+@\S+\.\S+$/.test(b.contactEmail))throw Object.assign(Error('Enter a valid contact email.'),{status:400});const org={...current,...Object.fromEntries(['orgName','contactEmail','contactPhone','processingFeePercent','processingFeeFixed','taxPercent'].map(k=>[k,b[k]]))};const credentials=[];for(const key of Object.keys(names)){const value=String(b[key]||'').trim();if(!value)continue;const valid=key==='stripeSecretKey'?/^sk_(test|live)_\S+$/.test(value):key==='stripeWebhookSecret'?/^whsec_\S+$/.test(value):/^pk_(test|live)_\S+$/.test(value);if(!valid)throw Object.assign(Error('Check the format of your Stripe '+key.replace('stripe','')+'.'),{status:400});credentials.push([key,key==='stripePublishableKey'?value:await seal(value)]);}await run("INSERT INTO settings VALUES('organization',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",JSON.stringify(org));for(const [key,value] of credentials)await run('INSERT INTO settings VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value',key,value);return {ok:true};}
export function charges(price:number,discount:number,org:any){const base=Math.max(0,price-discount),fee=base>0?Math.round(base*Number(org.processingFeePercent)/100)+Math.round(Number(org.processingFeeFixed)*100):0,tax=Math.round(base*Number(org.taxPercent)/100);return {price,discount,fee,tax,total:base+fee+tax};}
