'use client';
import SignaturePad from './signature-pad';
import type {Signature} from '@/lib/signature';
import {useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast} from 'sonner';

export default function ClubWaivers({data,user,admin,demo,api,onSaved}:{data:any,user:any,admin:boolean,demo:boolean,api:(path:string,body?:any)=>Promise<any>,onSaved:()=>Promise<void>}){
 const template=data.clubWaiver;
 const [signature,setSignature]=useState<Signature>([]);
 const [draft,setDraft]=useState(template?.text||''),[editVersion,setEditVersion]=useState(template?.version||0),[editing,setEditing]=useState(false),[player,setPlayer]=useState<any>(null),[review,setReview]=useState<any>(null),[signer,setSigner]=useState(''),[relationship,setRelationship]=useState('Parent'),[date,setDate]=useState(''),[agree,setAgree]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[history,setHistory]=useState<any[]|null>(null);
 function start(p:any){setSignature([]);setPlayer(p);setReview(template);setSigner(user?.name||'');setRelationship('Parent');setDate(new Date().toISOString().slice(0,10));setAgree(false);setError('');}
 async function publish(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('club-waivers/publish',{text:draft,version:editVersion});await onSaved();setEditing(false);setHistory(null);toast.success('Club waiver published.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function sign(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('club-waivers/sign',{playerId:player.id,version:review.version,signer,relationship,date,agree,signature});await onSaved();setPlayer(null);toast.success('Signed club waiver saved.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const saved=data.clubWaivers||[];
 return <section className="card" style={{padding:24,marginTop:20}}><div className="section-heading"><div><h2>Club waivers</h2><p>Sign for your child anytime, even when no registration is open.</p></div>{admin&&user?.role==='admin'&&<button className="btn secondary" onClick={()=>{setDraft(template?.text||'');setEditVersion(template?.version||0);setError('');setEditing(true)}}>{template?'Edit club waiver':'Set up club waiver'}</button>}</div><p className="muted">A club waiver does not enroll a player, reserve a spot, or require payment. Individual programs may also require a season waiver.</p>
 {demo?<p>Sign in to save and sign club waivers for your family.</p>:<>{!template&&<p>{admin?'Publish the club waiver text to let parents sign without a season.':'The club waiver is being prepared. You can add your child now and return here once the club publishes it.'}</p>}
 {!admin&&<div className="family-grid">{(data.players||[]).map((p:any)=>{const current=saved.find((w:any)=>w.player_id===p.id&&w.version===template?.version);return <div className="family-card" key={p.id}><h3>{p.name}</h3><p>{current?'Current club waiver signed':template?'Club waiver ready to sign':'Waiting for club waiver'}</p>{template&&!current&&<button className="btn primary" onClick={()=>start(p)}>Sign club waiver</button>}{saved.filter((w:any)=>w.player_id===p.id).map((w:any)=><p key={w.id}><a className="text-button" href={'/api/club-waivers/document/'+w.id} target="_blank" rel="noopener noreferrer">View / print signed waiver · v{w.version} · {w.date}</a></p>)}</div>})}</div>}
 {!admin&&!data.players?.length&&<p>Add a player above to fill out their waiver.</p>}
 {admin&&<><h3>Signed club waivers ({saved.length})</h3>{!saved.length&&<p>No club waivers signed yet.</p>}{saved.map((w:any)=><div className="price-line" key={w.id}><span><strong>{w.player_name}</strong> · {w.signer} · {w.date} · v{w.version}</span><a className="text-button" href={'/api/club-waivers/document/'+w.id} target="_blank" rel="noopener noreferrer">View / print</a></div>)}<button className="text-button" onClick={async()=>{try{setHistory((await api('club-waivers/history')).versions)}catch(e:any){toast.error(e.message)}}}>View template history</button>{history?.map(v=><details key={v.version}><summary>Version {v.version} · {v.created}</summary><pre className="waiver-text">{v.text}</pre></details>)}</>}
 </>}
 <Dialog open={editing} onOpenChange={v=>{if(!busy)setEditing(v)}}><DialogContent className="app-dialog wide"><DialogHeader><DialogTitle>Club waiver template</DialogTitle><DialogDescription>This waiver is available without a season or registration. Publishing creates a new version; signed copies stay unchanged.</DialogDescription></DialogHeader><form onSubmit={publish}><label className="field"><span>Complete waiver text</span><textarea rows={14} required maxLength={50000} value={draft} onChange={e=>setDraft(e.target.value)}/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="btn primary full" disabled={busy||!draft.trim()}>{busy?'Publishing…':'Publish club waiver'}</button></form></DialogContent></Dialog>
 <Dialog open={!!player} onOpenChange={v=>{if(!v&&!busy)setPlayer(null)}}><DialogContent className="app-dialog wide"><DialogHeader><DialogTitle>Club waiver · {player?.name}</DialogTitle><DialogDescription>Read the complete waiver, then sign below. No registration or payment is needed.</DialogDescription></DialogHeader><form onSubmit={sign}><pre className="waiver-text">{review?.text}</pre><p className="muted">Club waiver version {review?.version}</p><label className="field"><span>Full legal name of signer</span><input required value={signer} onChange={e=>setSigner(e.target.value)}/></label><div className="form-grid"><label className="field"><span>Relationship to player</span><select value={relationship} onChange={e=>setRelationship(e.target.value)}>{['Parent','Guardian','Adult player'].map(r=><option key={r}>{r}</option>)}</select></label><label className="field"><span>Signature date (UTC)</span><input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label></div><SignaturePad value={signature} onChange={setSignature} disabled={busy}/><label className="checkbox-line"><input type="checkbox" required checked={agree} onChange={e=>setAgree(e.target.checked)}/><span>I have read and agree to this waiver. By drawing my signature and typing my name, I intend to electronically sign it for the named player.</span></label>{error&&<p className="error" role="alert">{error} Close and reopen this form if the waiver has changed.</p>}<button className="btn primary full" disabled={busy||!agree}>{busy?'Saving…':'Sign and save waiver'}</button></form></DialogContent></Dialog>
 </section>;
}
