import {waiverText} from './rules';
export const demoSeasons=[{id:'fall-academy',name:'Fall Academy 2026',description:'Build confidence, develop technique, and find your love for the game. Our core development program combines Brazilian soccer fundamentals with small-sided games.',status:'Open',start:'2026-09-15',end:'2026-12-10',open:'2026-08-01',close:'2026-09-30',days:'Tuesday & Thursday',time:'4:30 PM – 6:00 PM',location:'North Miami Soccer Park',price:45000,capacity:60,enrolled:48,min_age:6,max_age:12,division:'U8 – U12',waiver:waiverText,version:1,questions:'[]',archived:0},{id:'junior-kickers',name:'Junior Kickers',description:'Big smiles. Small steps. A playful introduction to soccer for our youngest players, with fun games, coordination, and new friends.',status:'Open',start:'2026-09-19',end:'2026-12-12',open:'2026-08-01',close:'2026-10-01',days:'Saturday',time:'9:00 AM – 10:00 AM',location:'North Miami Soccer Park',price:27500,capacity:24,enrolled:18,min_age:3,max_age:5,division:'U4 – U6',waiver:waiverText,version:1,questions:'[]',archived:0},{id:'competitive',name:'Competitive Training',description:'Take your game further. Focused technical training, tactical development, and competitive match preparation.',status:'Full',start:'2026-09-14',end:'2026-12-11',open:'2026-08-01',close:'2026-09-30',days:'Monday, Wednesday & Friday',time:'5:00 PM – 6:30 PM',location:'North Miami Soccer Park',price:62500,capacity:32,enrolled:32,min_age:12,max_age:16,division:'U13 – U17',waiver:waiverText,version:1,questions:'[]',archived:0}];
const names=['Lucas Silva','Sofia Martinez','Noah Johnson','Isabella Santos','Mateo Rodriguez','Emma Wilson','Gabriel Costa','Olivia Brown'];
export const demoRegistrations=names.map((name,i)=>({id:'BSTC-'+(20260081+i),player_id:'demo-'+i,player_name:name,season_id:i%3===0?'junior-kickers':'fall-academy',season_name:i%3===0?'Junior Kickers':'Fall Academy 2026',division:i%3===0?'U4 – U6':'U8 – U12',parent_name:['Ana Silva','Carlos Martinez','Sarah Johnson','Rafael Santos','Elena Rodriguez','James Wilson','Maria Costa','Daniel Brown'][i],email:'parent@example.com',dob:'2017-06-12',status:'Confirmed',payment_status:i===2?'Unpaid':i===5?'Partially Paid':'Paid',amount:i%3===0?27500:45000,paid:i===2?0:i===5?22500:i%3===0?27500:45000,created:'2026-09-0'+(8-Math.floor(i/2))+'T12:30:00Z',waiver_status:i===2?'Missing':'Signed',signed:i===2?null:'2026-09-08T12:30:00Z'}));

export function demoWorkspace(parent=false){
 const registrations=(parent?demoRegistrations.slice(0,2).map((r,i)=>({...r,player_name:i?'Sofia Silva':'Lucas Silva',parent_name:'Ana Silva',email:'ana@example.test'})):demoRegistrations).map(r=>({...r,player:{data:JSON.stringify({guardian:r.parent_name,phone:'(555) 010-0200',emergencyName:'Demo emergency contact',emergencyPhone:'(555) 010-0300','Jersey size':'Youth M','Previous soccer experience':'One season'})},payments:r.paid?[{id:'demo-payment-'+r.id,amount:r.paid,method:'Stripe',created:r.created}]:[],notes:parent?undefined:[{id:'demo-note-'+r.id,text:'Sample administrative note. Visible to club staff only.',created:r.created}]}));
 return {seasons:demoSeasons,registrations,players:registrations.map(r=>({id:r.player_id,name:r.player_name,dob:r.dob,data:r.player.data})),payments:[],logs:parent?[]:[{id:'demo-log-1',actor:'Club administrator',action:'Opened Fall Academy registration',created:'2026-09-08T12:00:00Z'},{id:'demo-log-2',actor:'Club administrator',action:'Reviewed season waiver',created:'2026-09-07T12:00:00Z'}],users:parent?[]:[{id:'demo-admin',name:'Club Administrator',email:'admin@example.test',role:'admin'},{id:'demo-staff',name:'Demo Coach',email:'coach@example.test',role:'staff'},{id:'demo-parent',name:'Ana Silva',email:'ana@example.test',role:'parent'}],settings:{orgName:'Brazilian Soccer Training Center',contactEmail:'club@example.test',contactPhone:'(555) 010-0100',processingFeePercent:0,processingFeeFixed:0,taxPercent:0},integrations:{Stripe:false,Email:false,'Google Sheets':false}};
}
